module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('Users', [
      {
        id: '206802',
        firstname: 'Денис',
        lastname: 'Образцов',
        email: 'bibapokemon@gmail.com',
        password: '$2a$10$qqvPnw2UXYdCDXdOTcElN.DOg0N.O55uaDJjYGF2v8hWskrL9U4F.',
        description: 'Люблю помогать студентам в их начинаниях, ребята у вас все будет хорошо, вы все молодцы',
        isMentor: true,
        careerStart: '01.04.2020',
        companyId: '2qVZQ5g23R',
        isActive: true,
        position: 'Старший разработчик',
        userPhoto: 'https://ca.slack-edge.com/T025PA2D8A3-U02FWMW6RD1-459c28dbf206-512',
      },
      {
        id: '537982',
        firstname: 'Михаил',
        lastname: 'Пудов',
        email: 'mp@elbrusboot.camp',
        password: '$2a$10$qqvPnw2UXYdCDXdOTcElN.DOg0N.O55uaDJjYGF2v8hWskrL9U4F.',
        description: 'Что бы оказаться на вершине, я почти не спал и выпил немыслемое количество редбула',
        isMentor: true,
        careerStart: '01.04.2020',
        companyId: '2qVZQ5g23R',
        isActive: true,
        position: 'Старший разработчик',
        userPhoto: 'https://ca.slack-edge.com/T025PA2D8A3-U028W5K1P2R-28f5ba68073c-512',
      },
      {
        id: '589982',
        firstname: 'Артем',
        lastname: 'Коноплев',
        email: 'ak@elbrusboot.camp',
        password: '$2a$10$qqvPnw2UXYdCDXdOTcElN.DOg0N.O55uaDJjYGF2v8hWskrL9U4F.',
        description: 'Люблю программировать и помогать студентам, стучитесь пообщаеся.',
        isMentor: true,
        careerStart: '01.04.2020',
        companyId: 'Ma45Yp9o',
        isActive: true,
        position: 'Старший разработчик',
        userPhoto: 'https://ca.slack-edge.com/T025PA2D8A3-U026GMX5509-58a9cfa84f39-512',
      },
      {
        id: '589983',
        firstname: 'Тарас',
        lastname: 'Бананов',
        email: 'tg@elbrusboot.camp',
        password: '$2a$10$qqvPnw2UXYdCDXdOTcElN.DOg0N.O55uaDJjYGF2v8hWskrL9U4F.',
        description: 'Люблю покушать, особенно, что нибудь сладенькое, но и само собой люблю программировать.',
        isMentor: true,
        careerStart: '01.04.2020',
        companyId: 'Ma45YpK9',
        isActive: true,
        position: 'Старший разработчик',
        userPhoto: 'https://ca.slack-edge.com/T025PA2D8A3-U026A8CHQF6-6e9fba281123-512',
      },
      {
        id: '589984',
        firstname: 'Семен',
        lastname: 'Жолобов',
        email: 'sj@elbrusboot.camp',
        password: '$2a$10$qqvPnw2UXYdCDXdOTcElN.DOg0N.O55uaDJjYGF2v8hWskrL9U4F.',
        description: 'Люблю тяжелый рок и программирование, стучитесь.',
        isMentor: true,
        careerStart: '01.04.2020',
        companyId: 'Ma4123d-oK',
        isActive: true,
        position: 'Старший разработчик',
        userPhoto: 'https://ca.slack-edge.com/T025PA2D8A3-U02C4QUSJQ4-836724b37b31-512',
      },
      {
        id: '589985',
        firstname: 'Елена',
        lastname: 'Лушникова',
        email: 'elena.lushnikova@elbrusboot.camp',
        password: '$2a$10$qqvPnw2UXYdCDXdOTcElN.DOg0N.O55uaDJjYGF2v8hWskrL9U4F.',
        description: 'Исторический средневековый бой рулит, ну и конечно же мозила.',
        isMentor: true,
        careerStart: '01.04.2020',
        companyId: '898нгрsd',
        isActive: false,
        position: 'Старший разработчик',
        userPhoto: 'https://ca.slack-edge.com/T025PA2D8A3-U02CFKGD4TC-100f278cfde4-512',
      },
      {
        id: '589986',
        firstname: 'Юлия',
        lastname: 'Усачева',
        email: 'ju@elbrusboot.camp',
        password: '$2a$10$qqvPnw2UXYdCDXdOTcElN.DOg0N.O55uaDJjYGF2v8hWskrL9U4F.',
        description: 'Proactive variability checker',
        isMentor: true,
        careerStart: '01.04.2020',
        companyId: 'eRtgso0',
        isActive: false,
        position: 'Старший разработчик',
        userPhoto: 'https://ca.slack-edge.com/T025PA2D8A3-U02BV16KVFV-58b462140ccb-512',
      },
      {
        id: '589987',
        firstname: 'Марсель',
        lastname: 'Бурно',
        email: 'burdo.marsel@gmail.com',
        password: '$2a$10$qqvPnw2UXYdCDXdOTcElN.DOg0N.O55uaDJjYGF2v8hWskrL9U4F.',
        description: 'Люблю программировать и помогать студентам',
        isMentor: true,
        careerStart: '01.04.2020',
        companyId: '2qVZQ5g23R',
        isActive: true,
        position: 'Старший разработчик',
        userPhoto: 'https://ca.slack-edge.com/T025PA2D8A3-U02A2UDA2NA-bc0f067b2738-512',
      },
      {
        id: '58998',
        firstname: 'Марк',
        lastname: 'Цукенберг',
        email: 'mark@gmail.com',
        password: '$2a$10$qqvPnw2UXYdCDXdOTcElN.DOg0N.O55uaDJjYGF2v8hWskrL9U4F.',
        description: 'Руководитель компании Facebook Inc. Программист, предприниматель в области интернет-технологий, долларовый миллиардер, филантроп.',
        isMentor: true,
        careerStart: '01.04.2010',
        companyId: 'eRtgsds0sdk',
        isActive: true,
        position: 'Старший разработчик',
        userPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7AehuKfxrNdOnE9KIVe-_QX799Gr2M2YnNA&usqp=CAU',
      },
      {
        id: '365742',
        firstname: 'Билл',
        lastname: 'Гейтс',
        email: 'Bill@gmail.com',
        password: '$2a$10$qqvPnw2UXYdCDXdOTcElN.DOg0N.O55uaDJjYGF2v8hWskrL9U4F.',
        description: 'Предприниматель, общественный деятель, филантроп, в свободное время занимаюсь менторством',
        isMentor: true,
        careerStart: '02.08.2014',
        companyId: 'ebDFCJ45OF',
        isActive: true,
        position: 'Старший разработчик',
        userPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8lRUd_5tlyGbVQTXZ0iXesY_Y0IhJekFxUQ&usqp=CAU',
      },
      {
        id: '145976',
        firstname: 'Clementine',
        lastname: 'Bauch',
        email: 'Nathan@yesenia.net',
        password: '$2a$10$qqvPnw2UXYdCDXdOTcElN.DOg0N.O55uaDJjYGF2v8hWskrL9U4F.',
        description: 'Face to face bifurcated interface',
        isMentor: false,
        isActive: true,
        userPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJCTlLL7h7H3LpxCnyVpyg8EoDvbNHkFqrrw&usqp=CAU',

      },
      {
        id: '14597',
        firstname: 'Иван',
        lastname: 'Иванов',
        email: 'Nan@yesea.net',
        password: '$2a$10$qqvPnw2UXYdCDXdOTcElN.DOg0N.O55uaDJjYGF2v8hWskrL9U4F.',
        description: 'Face to face bifurcated interface',
        isMentor: false,
        isActive: true,
        userPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCqaDf_PZap4h22_uQ4c9qDC__sb61AIXX4g&usqp=CAU',

      },
      {
        id: '14598',
        firstname: 'Перт',
        lastname: 'Петров',
        email: 'Petr@yesea.net',
        password: '$2a$10$qqvPnw2UXYdCDXdOTcElN.DOg0N.O55uaDJjYGF2v8hWskrL9U4F.',
        description: 'Face to face bifurcated interface',
        isMentor: false,
        isActive: true,
        userPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7yLxef5eB183N5pPA27eipYx8WeKf9layyA&usqp=CAU',

      },
      {
        id: '14599',
        firstname: 'Жорик',
        lastname: 'Вартанов',
        email: 'Pertsd@yesea.net',
        password: '$2a$10$qqvPnw2UXYdCDXdOTcElN.DOg0N.O55uaDJjYGF2v8hWskrL9U4F.',
        description: 'Face to face bifurcated interface',
        isMentor: false,
        isActive: true,
        userPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRki1P_x5Fad4u8XCzdEdsycXyCcwYTCZ9N8A&usqp=CAU',

      },
      {
        id: '145981',
        firstname: 'Алексей',
        lastname: 'Никитин',
        email: 'ggar@mail.ru',
        password: '$2a$10$qqvPnw2UXYdCDXdOTcElN.DOg0N.O55uaDJjYGF2v8hWskrL9U4F.',
        description: 'Face to face bifurcated interface',
        isMentor: false,
        isActive: true,
        userPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTaDAe985RZeJTGPUL4KJp7OYn-NewEQtfHvA&usqp=CAU',

      },
      {
        id: '145982',
        firstname: 'Херсон',
        lastname: 'Литвенежко',
        email: 'lit@mail.ru',
        password: '$2a$10$qqvPnw2UXYdCDXdOTcElN.DOg0N.O55uaDJjYGF2v8hWskrL9U4F.',
        description: 'Face to face bifurcated interface',
        isMentor: false,
        isActive: true,
        userPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_XmUZZ4l_ArL9IJDUpHaXGQ-T0bLs_gfmng&usqp=CAU',

      },
      {
        id: '145983',
        firstname: 'Глеб',
        lastname: 'Аршавин',
        email: 'lfdt@mail.ru',
        password: '$2a$10$qqvPnw2UXYdCDXdOTcElN.DOg0N.O55uaDJjYGF2v8hWskrL9U4F.',
        description: 'Face to face bifurcated interface',
        isMentor: false,
        isActive: true,
        userPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRABDC8UoE8RUEduze0q5vb4DvvPTSytT7eBQ&usqp=CAU',

      },
      {
        id: '145984',
        firstname: 'Марата',
        lastname: 'Раисова',
        email: 'rais@mail.ru',
        password: '$2a$10$qqvPnw2UXYdCDXdOTcElN.DOg0N.O55uaDJjYGF2v8hWskrL9U4F.',
        description: 'Face to face bifurcated interface',
        isMentor: false,
        userPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8JroW6h0uubO0ps2cWhP7RzS9eV2LAgMpeQ&usqp=CAU',
      },
      {
        id: '145985',
        firstname: 'Александр',
        lastname: 'Шатц',
        email: 'shatc@mail.ru',
        password: '$2a$10$qqvPnw2UXYdCDXdOTcElN.DOg0N.O55uaDJjYGF2v8hWskrL9U4F.',
        description: 'Face to face bifurcated interface',
        isMentor: false,
        userPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRN0a_ipMtjgyQKr2xQ4s0Hr4Pv6yRoH2xDNw&usqp=CAU',
      },
      {
        id: '145986',
        firstname: 'Алексей',
        lastname: 'Сергеев',
        email: 'sergeev@mail.ru',
        password: '$2a$10$qqvPnw2UXYdCDXdOTcElN.DOg0N.O55uaDJjYGF2v8hWskrL9U4F.',
        description: 'Face to face bifurcated interface',
        isMentor: false,
        userPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3CBS0Q8N6OTcNBgO6FdUtFbpqanBRv7TdOw&usqp=CAU',
      },
      {
        id: '145987',
        firstname: 'Роман',
        lastname: 'Матвеев',
        email: 'rom@mail.ru',
        password: '$2a$10$qqvPnw2UXYdCDXdOTcElN.DOg0N.O55uaDJjYGF2v8hWskrL9U4F.',
        description: 'Face to face bifurcated interface',
        isMentor: false,
        userPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXlluKJo9vEdVAOwt6bEjmvNR94xN-1cXiYQ&usqp=CAU',
      },
      {
        id: '145988',
        firstname: 'Вероника',
        lastname: 'Антонова',
        email: 'matveeva@mail.ru',
        password: '$2a$10$qqvPnw2UXYdCDXdOTcElN.DOg0N.O55uaDJjYGF2v8hWskrL9U4F.',
        description: 'Face to face bifurcated interface',
        isMentor: false,
        userPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXlluKJo9vEdVAOwt6bEjmvNR94xN-1cXiYQ&usqp=CAU',
      },
      {
        id: '145989',
        firstname: 'Алена',
        lastname: 'Апина',
        email: 'api@mail.ru',
        password: '$2a$10$qqvPnw2UXYdCDXdOTcElN.DOg0N.O55uaDJjYGF2v8hWskrL9U4F.',
        description: 'Face to face bifurcated interface',
        isMentor: false,
        userPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKe7hB660cA6YLGv4n1r0TqLb0eT0-Arwdeg&usqp=CAU',
      },
      {
        id: '1459891',
        firstname: 'Алена',
        lastname: 'Корж',
        email: 'korzh@mail.ru',
        password: '$2a$10$qqvPnw2UXYdCDXdOTcElN.DOg0N.O55uaDJjYGF2v8hWskrL9U4F.',
        description: 'Face to face bifurcated interface',
        isMentor: false,
        userPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxiTSEvxgrBkaw7Y8IbHiw71LBoS4WN5oilQ&usqp=CAU',
      },
      {
        id: '1459892',
        firstname: 'Борис',
        lastname: 'Невзоров',
        email: 'nevzorov@mail.ru',
        password: '$2a$10$qqvPnw2UXYdCDXdOTcElN.DOg0N.O55uaDJjYGF2v8hWskrL9U4F.',
        description: 'Face to face bifurcated interface',
        isMentor: false,
        userPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQuG91gik26X8fYsSf3g1ZaxlUGPXMZUM-Wvg&usqp=CAU',
      },
      {
        id: '1459893',
        firstname: 'Светлана',
        lastname: 'Онисимова',
        email: 'onis@mail.ru',
        password: '$2a$10$qqvPnw2UXYdCDXdOTcElN.DOg0N.O55uaDJjYGF2v8hWskrL9U4F.',
        description: 'Face to face bifurcated interface',
        isMentor: false,
        userPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1D8ufwFNxXdRxfW-RF0cMYD9TZs3NAHwk8A&usqp=CAU',
      },
      {
        id: '1459894',
        firstname: 'Станислав',
        lastname: 'Ермолин',
        email: 'ermolin@mail.ru',
        password: '$2a$10$qqvPnw2UXYdCDXdOTcElN.DOg0N.O55uaDJjYGF2v8hWskrL9U4F.',
        description: 'Face to face bifurcated interface',
        isMentor: false,
        userPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRMupKSRaMSCPrjfxmeXGRBvUxU72G7UR4cg&usqp=CAU',
      },
      {
        id: '1459895',
        firstname: 'Брокколи',
        lastname: 'Блог',
        email: 'blog@mail.ru',
        password: '$2a$10$qqvPnw2UXYdCDXdOTcElN.DOg0N.O55uaDJjYGF2v8hWskrL9U4F.',
        description: 'Face to face bifurcated interface',
        isMentor: false,
        userPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwEUazSGCfNnWajM1gZ2qTGvW08_8uXx6zww&usqp=CAU',
      },
      {
        id: '1459896',
        firstname: 'Алексей',
        lastname: 'Кобзев',
        email: 'kobzev@mail.ru',
        password: '$2a$10$qqvPnw2UXYdCDXdOTcElN.DOg0N.O55uaDJjYGF2v8hWskrL9U4F.',
        description: 'Face to face bifurcated interface',
        isMentor: false,
        userPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_SuzV8m8E4RDBgQ91cT069AJKZzeDyIP7hA&usqp=CAU',
      },
      {
        id: '1459897',
        firstname: 'Алексей',
        lastname: 'Наваленко',
        email: 'nav@mail.ru',
        password: '$2a$10$qqvPnw2UXYdCDXdOTcElN.DOg0N.O55uaDJjYGF2v8hWskrL9U4F.',
        description: 'Face to face bifurcated interface',
        isMentor: false,
        userPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSc9mfrltr281q5YSlxjzHB7-VrKmtCOmcvZQ&usqp=CAU',
      },

    ], {});
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('Users', null, {});
  },
};
